// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAseiMUDnUmY7eClB-jcria7_bYA07m8L0',
    appId: '1:1005315471143:web:500c0927d6039e74dd1b02',
    messagingSenderId: '1005315471143',
    projectId: 'dapurpintar-f2f57',
    authDomain: 'dapurpintar-f2f57.firebaseapp.com',
    storageBucket: 'dapurpintar-f2f57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj8sThaCpbJTjHzy9RyRAS1-Wyyes6wnQ',
    appId: '1:1005315471143:android:0b95b2f405d0b64bdd1b02',
    messagingSenderId: '1005315471143',
    projectId: 'dapurpintar-f2f57',
    storageBucket: 'dapurpintar-f2f57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76g8CREq10wSgKM0JRByslilJg_H--uo',
    appId: '1:1005315471143:ios:eb3616267334ca22dd1b02',
    messagingSenderId: '1005315471143',
    projectId: 'dapurpintar-f2f57',
    storageBucket: 'dapurpintar-f2f57.firebasestorage.app',
    iosBundleId: 'com.example.dapurPintar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA76g8CREq10wSgKM0JRByslilJg_H--uo',
    appId: '1:1005315471143:ios:eb3616267334ca22dd1b02',
    messagingSenderId: '1005315471143',
    projectId: 'dapurpintar-f2f57',
    storageBucket: 'dapurpintar-f2f57.firebasestorage.app',
    iosBundleId: 'com.example.dapurPintar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAseiMUDnUmY7eClB-jcria7_bYA07m8L0',
    appId: '1:1005315471143:web:b3e646f849856350dd1b02',
    messagingSenderId: '1005315471143',
    projectId: 'dapurpintar-f2f57',
    authDomain: 'dapurpintar-f2f57.firebaseapp.com',
    storageBucket: 'dapurpintar-f2f57.firebasestorage.app',
  );
}
